#!/bin/bash
title=flatpak
description="- Includes SJTU Flathub repository"
status=off

main() {
    commandFailure="Flatpak installation has failed."
    echo -e "Installing flatpak... \n"
    xbps-install -Sy -R $installRepo -r /mnt flatpak || failureCheck
    echo -e "Flatpak has been installed. \n"
    
    commandFailure="Adding SJTU flatpak repository has failed."
    echo -e "Adding SJTU Flathub repo for flatpak... \n"
    chroot /mnt /bin/bash -c "flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub" || failureCheck
    echo -e "SJTU Flathub repo has been added. \n"

    return 0
}
