#!/bin/bash
# kernel_lockdown.sh
#
# 描述：
# 该脚本用于配置 Linux 内核的 "lockdown" 模式。Lockdown 模式可以限制用户态进程对内核的某些操作，从而增强系统的安全性。用户可以选择以下两种模式：
# 1. **integrity 模式**：禁止用户态进程修改正在运行的内核（例如，禁止通过加载模块来改变内核状态），确保系统完整性。
# 2. **confidentiality 模式**：在 integrity 模式的基础上进一步限制，防止提取内核中的机密信息。
#
# 本脚本通过设置内核引导参数 `lockdown=integrity` 或 `lockdown=confidentiality` 来启用对应的 lockdown 模式。根据系统的引导加载程序类型（grub、efistub、uki），脚本会修改不同的配置文件，并应用更改。
#
# - **grub**：修改 GRUB 配置，并通过 `update-grub` 使更改生效。
# - **efistub**：修改 `efibootmgr-kernel-hook` 配置，并通过 `xbps-reconfigure` 重新配置内核。
# - **uki**：修改 `kernelparams` 文件，并重建 UKI 镜像以更新内核参数。
#
# Lockdown 模式可以通过提高系统的内核保护等级来增强系统的安全性，尤其在面临恶意行为时有更好的防护作用。

title=kernel_lockdown
description="- Provides a choice to set the kernel lockdown mode"
status=off

main() {

    lockdownChoice=$(drawDialog --no-cancel --title "Kernel Lockdown Mode" --menu "" 0 0 0 "integrity" "- Userland modifying the running kernel is disabled." "confidentiality" "- Extracting confidential information from the kernel is also disabled." "None" "")

    commandFailure="Enabling kernel lockdown mode has failed."
    if [ "$lockdownChoice" == "integrity" ]; then
            case $bootloaderChoice in
                grub)
                    sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=integrity/g' /mnt/etc/default/grub || failureCheck
                    chroot /mnt /bin/bash -c "update-grub" || failureCheck
                    ;;
                efistub)
                    sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=integrity/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
                    chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
                    ;;
                uki)
                    sed -i -e 's/loglevel=4/loglevel=4 lockdown=integrity/g' /mnt/root/kernelparams || failureCheck
                    chroot /mnt /bin/bash -c 'rm /boot/efi/EFI/boot/bootx64.efi && ukify build --linux="$(find /boot/vmlinuz*)" --initrd="$(find /boot/initramfs*)" --cmdline="$(cat /root/kernelparams)" --output=/boot/efi/EFI/boot/bootx64.efi' || failureCheck
                    ;;
            esac
    elif [ "$lockdownChoice" == "confidentiality" ]; then
            case $bootloaderChoice in
                grub)
                    sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/grub || failureCheck
                    chroot /mnt /bin/bash -c "update-grub" || failureCheck
                    ;;
                efistub)
                    sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
                    chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
                    ;;
                uki)
                    sed -i -e 's/loglevel=4/loglevel=4 lockdown=confidentiality/g' /mnt/root/kernelparams || failureCheck
                    chroot /mnt /bin/bash -c 'rm /boot/efi/EFI/boot/bootx64.efi && ukify build --linux="$(find /boot/vmlinuz*)" --initrd="$(find /boot/initramfs*)" --cmdline="$(cat /root/kernelparams)" --output=/boot/efi/EFI/boot/bootx64.efi' || failureCheck
                    ;;
            esac
    fi

    return 0
}
